// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auctions.sql

package repository

import (
	"context"
	"database/sql"
	"time"
)

const closeAuctionByID = `-- name: CloseAuctionByID :exec
UPDATE auctions SET status = 2 WHERE id = ?
`

func (q *Queries) CloseAuctionByID(ctx context.Context, id []byte) error {
	_, err := q.db.ExecContext(ctx, closeAuctionByID, id)
	return err
}

const countActiveAuctions = `-- name: CountActiveAuctions :one
SELECT COUNT(*) FROM auctions WHERE status = 1
`

func (q *Queries) CountActiveAuctions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveAuctions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuction = `-- name: CreateAuction :exec
INSERT INTO auctions (id, seller_id, title, description, image_url, starting_price, current_price, status, start_time, end_time)
VALUES (?, ?, ?, ?, ?, ?, ?, 1, NOW(), ?)
`

type CreateAuctionParams struct {
	ID            []byte         `json:"id"`
	SellerID      []byte         `json:"seller_id"`
	Title         string         `json:"title"`
	Description   sql.NullString `json:"description"`
	ImageUrl      sql.NullString `json:"image_url"`
	StartingPrice int64          `json:"starting_price"`
	CurrentPrice  int64          `json:"current_price"`
	EndTime       time.Time      `json:"end_time"`
}

func (q *Queries) CreateAuction(ctx context.Context, arg CreateAuctionParams) error {
	_, err := q.db.ExecContext(ctx, createAuction,
		arg.ID,
		arg.SellerID,
		arg.Title,
		arg.Description,
		arg.ImageUrl,
		arg.StartingPrice,
		arg.CurrentPrice,
		arg.EndTime,
	)
	return err
}

const getAuctionByID = `-- name: GetAuctionByID :one
SELECT a.id, a.seller_id, u.username as seller_name,
       a.title, a.description, a.image_url,
       a.starting_price, a.current_price, a.winner_id,
       COALESCE(w.username, '') as winner_name,
       a.status, a.start_time, a.end_time, a.created_at,
       (SELECT COUNT(*) FROM bids WHERE auction_id = a.id) as bid_count
FROM auctions a
JOIN users u ON u.id = a.seller_id
LEFT JOIN users w ON w.id = a.winner_id
WHERE a.id = ?
`

type GetAuctionByIDRow struct {
	ID            []byte         `json:"id"`
	SellerID      []byte         `json:"seller_id"`
	SellerName    string         `json:"seller_name"`
	Title         string         `json:"title"`
	Description   sql.NullString `json:"description"`
	ImageUrl      sql.NullString `json:"image_url"`
	StartingPrice int64          `json:"starting_price"`
	CurrentPrice  int64          `json:"current_price"`
	WinnerID      sql.NullString `json:"winner_id"`
	WinnerName    string         `json:"winner_name"`
	Status        int16          `json:"status"`
	StartTime     time.Time      `json:"start_time"`
	EndTime       time.Time      `json:"end_time"`
	CreatedAt     time.Time      `json:"created_at"`
	BidCount      int64          `json:"bid_count"`
}

func (q *Queries) GetAuctionByID(ctx context.Context, id []byte) (GetAuctionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getAuctionByID, id)
	var i GetAuctionByIDRow
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.SellerName,
		&i.Title,
		&i.Description,
		&i.ImageUrl,
		&i.StartingPrice,
		&i.CurrentPrice,
		&i.WinnerID,
		&i.WinnerName,
		&i.Status,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.BidCount,
	)
	return i, err
}

const getExpiredActiveAuctions = `-- name: GetExpiredActiveAuctions :many
SELECT id, winner_id, current_price, title
FROM auctions
WHERE status = 1 AND end_time <= NOW()
`

type GetExpiredActiveAuctionsRow struct {
	ID           []byte         `json:"id"`
	WinnerID     sql.NullString `json:"winner_id"`
	CurrentPrice int64          `json:"current_price"`
	Title        string         `json:"title"`
}

func (q *Queries) GetExpiredActiveAuctions(ctx context.Context) ([]GetExpiredActiveAuctionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getExpiredActiveAuctions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetExpiredActiveAuctionsRow{}
	for rows.Next() {
		var i GetExpiredActiveAuctionsRow
		if err := rows.Scan(
			&i.ID,
			&i.WinnerID,
			&i.CurrentPrice,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveAuctions = `-- name: ListActiveAuctions :many
SELECT a.id, a.seller_id, u.username as seller_name,
       a.title, a.description, a.image_url,
       a.starting_price, a.current_price, a.winner_id,
       a.status, a.start_time, a.end_time, a.created_at,
       (SELECT COUNT(*) FROM bids WHERE auction_id = a.id) as bid_count
FROM auctions a
JOIN users u ON u.id = a.seller_id
WHERE a.status = 1
ORDER BY a.end_time ASC
LIMIT ? OFFSET ?
`

type ListActiveAuctionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListActiveAuctionsRow struct {
	ID            []byte         `json:"id"`
	SellerID      []byte         `json:"seller_id"`
	SellerName    string         `json:"seller_name"`
	Title         string         `json:"title"`
	Description   sql.NullString `json:"description"`
	ImageUrl      sql.NullString `json:"image_url"`
	StartingPrice int64          `json:"starting_price"`
	CurrentPrice  int64          `json:"current_price"`
	WinnerID      sql.NullString `json:"winner_id"`
	Status        int16          `json:"status"`
	StartTime     time.Time      `json:"start_time"`
	EndTime       time.Time      `json:"end_time"`
	CreatedAt     time.Time      `json:"created_at"`
	BidCount      int64          `json:"bid_count"`
}

func (q *Queries) ListActiveAuctions(ctx context.Context, arg ListActiveAuctionsParams) ([]ListActiveAuctionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveAuctions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveAuctionsRow{}
	for rows.Next() {
		var i ListActiveAuctionsRow
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.SellerName,
			&i.Title,
			&i.Description,
			&i.ImageUrl,
			&i.StartingPrice,
			&i.CurrentPrice,
			&i.WinnerID,
			&i.Status,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
			&i.BidCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuctionsByUser = `-- name: ListAuctionsByUser :many
SELECT a.id, a.seller_id, u.username as seller_name,
       a.title, a.description, a.image_url,
       a.starting_price, a.current_price, a.winner_id,
       a.status, a.start_time, a.end_time, a.created_at,
       (SELECT COUNT(*) FROM bids WHERE auction_id = a.id) as bid_count
FROM auctions a
JOIN users u ON u.id = a.seller_id
WHERE a.seller_id = ?
ORDER BY a.created_at DESC
LIMIT ? OFFSET ?
`

type ListAuctionsByUserParams struct {
	SellerID []byte `json:"seller_id"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

type ListAuctionsByUserRow struct {
	ID            []byte         `json:"id"`
	SellerID      []byte         `json:"seller_id"`
	SellerName    string         `json:"seller_name"`
	Title         string         `json:"title"`
	Description   sql.NullString `json:"description"`
	ImageUrl      sql.NullString `json:"image_url"`
	StartingPrice int64          `json:"starting_price"`
	CurrentPrice  int64          `json:"current_price"`
	WinnerID      sql.NullString `json:"winner_id"`
	Status        int16          `json:"status"`
	StartTime     time.Time      `json:"start_time"`
	EndTime       time.Time      `json:"end_time"`
	CreatedAt     time.Time      `json:"created_at"`
	BidCount      int64          `json:"bid_count"`
}

func (q *Queries) ListAuctionsByUser(ctx context.Context, arg ListAuctionsByUserParams) ([]ListAuctionsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuctionsByUser, arg.SellerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuctionsByUserRow{}
	for rows.Next() {
		var i ListAuctionsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.SellerName,
			&i.Title,
			&i.Description,
			&i.ImageUrl,
			&i.StartingPrice,
			&i.CurrentPrice,
			&i.WinnerID,
			&i.Status,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
			&i.BidCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAuctionForBid = `-- name: LockAuctionForBid :one
SELECT id, seller_id, current_price, winner_id, status, end_time
FROM auctions
WHERE id = ? AND status = 1
FOR UPDATE
`

type LockAuctionForBidRow struct {
	ID           []byte         `json:"id"`
	SellerID     []byte         `json:"seller_id"`
	CurrentPrice int64          `json:"current_price"`
	WinnerID     sql.NullString `json:"winner_id"`
	Status       int16          `json:"status"`
	EndTime      time.Time      `json:"end_time"`
}

func (q *Queries) LockAuctionForBid(ctx context.Context, id []byte) (LockAuctionForBidRow, error) {
	row := q.db.QueryRowContext(ctx, lockAuctionForBid, id)
	var i LockAuctionForBidRow
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.CurrentPrice,
		&i.WinnerID,
		&i.Status,
		&i.EndTime,
	)
	return i, err
}

const updateAuctionBid = `-- name: UpdateAuctionBid :exec
UPDATE auctions
SET current_price = ?, winner_id = ?
WHERE id = ?
`

type UpdateAuctionBidParams struct {
	CurrentPrice int64          `json:"current_price"`
	WinnerID     sql.NullString `json:"winner_id"`
	ID           []byte         `json:"id"`
}

func (q *Queries) UpdateAuctionBid(ctx context.Context, arg UpdateAuctionBidParams) error {
	_, err := q.db.ExecContext(ctx, updateAuctionBid, arg.CurrentPrice, arg.WinnerID, arg.ID)
	return err
}
