// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: bids.sql

package repository

import (
	"context"
	"time"
)

const countBidsByAuction = `-- name: CountBidsByAuction :one
SELECT COUNT(*) FROM bids WHERE auction_id = ?
`

func (q *Queries) CountBidsByAuction(ctx context.Context, auctionID []byte) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBidsByAuction, auctionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBid = `-- name: CreateBid :exec
INSERT INTO bids (id, auction_id, user_id, amount)
VALUES (?, ?, ?, ?)
`

type CreateBidParams struct {
	ID        []byte `json:"id"`
	AuctionID []byte `json:"auction_id"`
	UserID    []byte `json:"user_id"`
	Amount    int64  `json:"amount"`
}

func (q *Queries) CreateBid(ctx context.Context, arg CreateBidParams) error {
	_, err := q.db.ExecContext(ctx, createBid,
		arg.ID,
		arg.AuctionID,
		arg.UserID,
		arg.Amount,
	)
	return err
}

const listBidsByAuction = `-- name: ListBidsByAuction :many
SELECT b.id, b.auction_id, b.user_id, u.username, b.amount, b.created_at
FROM bids b
JOIN users u ON u.id = b.user_id
WHERE b.auction_id = ?
ORDER BY b.amount DESC
LIMIT ? OFFSET ?
`

type ListBidsByAuctionParams struct {
	AuctionID []byte `json:"auction_id"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

type ListBidsByAuctionRow struct {
	ID        []byte    `json:"id"`
	AuctionID []byte    `json:"auction_id"`
	UserID    []byte    `json:"user_id"`
	Username  string    `json:"username"`
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) ListBidsByAuction(ctx context.Context, arg ListBidsByAuctionParams) ([]ListBidsByAuctionRow, error) {
	rows, err := q.db.QueryContext(ctx, listBidsByAuction, arg.AuctionID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBidsByAuctionRow{}
	for rows.Next() {
		var i ListBidsByAuctionRow
		if err := rows.Scan(
			&i.ID,
			&i.AuctionID,
			&i.UserID,
			&i.Username,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
