// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: deposits.sql

package repository

import (
	"context"
	"time"
)

const createDeposit = `-- name: CreateDeposit :exec
INSERT INTO deposits (id, user_id, amount, status, stripe_payment_id)
VALUES (?, ?, ?, 'pending', ?)
`

type CreateDepositParams struct {
	ID              []byte `json:"id"`
	UserID          []byte `json:"user_id"`
	Amount          int64  `json:"amount"`
	StripePaymentID string `json:"stripe_payment_id"`
}

func (q *Queries) CreateDeposit(ctx context.Context, arg CreateDepositParams) error {
	_, err := q.db.ExecContext(ctx, createDeposit,
		arg.ID,
		arg.UserID,
		arg.Amount,
		arg.StripePaymentID,
	)
	return err
}

const getDepositByID = `-- name: GetDepositByID :one
SELECT d.id, d.user_id, u.username, d.amount, d.status, d.stripe_payment_id, d.created_at, d.updated_at
FROM deposits d
JOIN users u ON u.id = d.user_id
WHERE d.id = ?
`

type GetDepositByIDRow struct {
	ID              []byte    `json:"id"`
	UserID          []byte    `json:"user_id"`
	Username        string    `json:"username"`
	Amount          int64     `json:"amount"`
	Status          string    `json:"status"`
	StripePaymentID string    `json:"stripe_payment_id"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

func (q *Queries) GetDepositByID(ctx context.Context, id []byte) (GetDepositByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getDepositByID, id)
	var i GetDepositByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.Amount,
		&i.Status,
		&i.StripePaymentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDepositByStripeID = `-- name: GetDepositByStripeID :one
SELECT d.id, d.user_id, u.username, d.amount, d.status, d.stripe_payment_id, d.created_at, d.updated_at
FROM deposits d
JOIN users u ON u.id = d.user_id
WHERE d.stripe_payment_id = ?
`

type GetDepositByStripeIDRow struct {
	ID              []byte    `json:"id"`
	UserID          []byte    `json:"user_id"`
	Username        string    `json:"username"`
	Amount          int64     `json:"amount"`
	Status          string    `json:"status"`
	StripePaymentID string    `json:"stripe_payment_id"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

func (q *Queries) GetDepositByStripeID(ctx context.Context, stripePaymentID string) (GetDepositByStripeIDRow, error) {
	row := q.db.QueryRowContext(ctx, getDepositByStripeID, stripePaymentID)
	var i GetDepositByStripeIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.Amount,
		&i.Status,
		&i.StripePaymentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDepositsByUser = `-- name: ListDepositsByUser :many
SELECT id, user_id, amount, status, stripe_payment_id, created_at, updated_at
FROM deposits
WHERE user_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListDepositsByUserParams struct {
	UserID []byte `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListDepositsByUser(ctx context.Context, arg ListDepositsByUserParams) ([]Deposit, error) {
	rows, err := q.db.QueryContext(ctx, listDepositsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deposit{}
	for rows.Next() {
		var i Deposit
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Status,
			&i.StripePaymentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDepositByStripeID = `-- name: LockDepositByStripeID :one
SELECT id, user_id, amount, status, stripe_payment_id
FROM deposits
WHERE stripe_payment_id = ?
FOR UPDATE
`

type LockDepositByStripeIDRow struct {
	ID              []byte `json:"id"`
	UserID          []byte `json:"user_id"`
	Amount          int64  `json:"amount"`
	Status          string `json:"status"`
	StripePaymentID string `json:"stripe_payment_id"`
}

func (q *Queries) LockDepositByStripeID(ctx context.Context, stripePaymentID string) (LockDepositByStripeIDRow, error) {
	row := q.db.QueryRowContext(ctx, lockDepositByStripeID, stripePaymentID)
	var i LockDepositByStripeIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Status,
		&i.StripePaymentID,
	)
	return i, err
}

const updateDepositStatus = `-- name: UpdateDepositStatus :exec
UPDATE deposits SET status = ? WHERE id = ?
`

type UpdateDepositStatusParams struct {
	Status string `json:"status"`
	ID     []byte `json:"id"`
}

func (q *Queries) UpdateDepositStatus(ctx context.Context, arg UpdateDepositStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateDepositStatus, arg.Status, arg.ID)
	return err
}
