// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Auction struct {
	ID            []byte         `json:"id"`
	SellerID      []byte         `json:"seller_id"`
	Title         string         `json:"title"`
	Description   sql.NullString `json:"description"`
	ImageUrl      sql.NullString `json:"image_url"`
	StartingPrice int64          `json:"starting_price"`
	CurrentPrice  int64          `json:"current_price"`
	WinnerID      sql.NullString `json:"winner_id"`
	Status        int16          `json:"status"`
	StartTime     time.Time      `json:"start_time"`
	EndTime       time.Time      `json:"end_time"`
	CreatedAt     time.Time      `json:"created_at"`
}

type Bid struct {
	ID        []byte    `json:"id"`
	AuctionID []byte    `json:"auction_id"`
	UserID    []byte    `json:"user_id"`
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

type Deposit struct {
	ID              []byte    `json:"id"`
	UserID          []byte    `json:"user_id"`
	Amount          int64     `json:"amount"`
	Status          string    `json:"status"`
	StripePaymentID string    `json:"stripe_payment_id"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type User struct {
	ID          []byte          `json:"id"`
	Username    string          `json:"username"`
	Email       string          `json:"email"`
	Password    string          `json:"password"`
	Balance     int64           `json:"balance"`
	CreatedAt   time.Time       `json:"created_at"`
	TotpSecret  sql.NullString  `json:"totp_secret"`
	TotpEnabled bool            `json:"totp_enabled"`
	BackupCodes json.RawMessage `json:"backup_codes"`
}
