// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: totp.sql

package repository

import (
	"context"
	"database/sql"
	"encoding/json"
)

const disableUserTotp = `-- name: DisableUserTotp :exec
UPDATE users SET totp_enabled = FALSE, totp_secret = NULL, backup_codes = NULL WHERE id = ?
`

func (q *Queries) DisableUserTotp(ctx context.Context, id []byte) error {
	_, err := q.db.ExecContext(ctx, disableUserTotp, id)
	return err
}

const enableUserTotp = `-- name: EnableUserTotp :exec
UPDATE users SET totp_enabled = TRUE, backup_codes = ? WHERE id = ?
`

type EnableUserTotpParams struct {
	BackupCodes json.RawMessage `json:"backup_codes"`
	ID          []byte          `json:"id"`
}

func (q *Queries) EnableUserTotp(ctx context.Context, arg EnableUserTotpParams) error {
	_, err := q.db.ExecContext(ctx, enableUserTotp, arg.BackupCodes, arg.ID)
	return err
}

const getUserTotpInfo = `-- name: GetUserTotpInfo :one
SELECT id, username, totp_secret, totp_enabled, backup_codes
FROM users WHERE id = ?
`

type GetUserTotpInfoRow struct {
	ID          []byte          `json:"id"`
	Username    string          `json:"username"`
	TotpSecret  sql.NullString  `json:"totp_secret"`
	TotpEnabled bool            `json:"totp_enabled"`
	BackupCodes json.RawMessage `json:"backup_codes"`
}

func (q *Queries) GetUserTotpInfo(ctx context.Context, id []byte) (GetUserTotpInfoRow, error) {
	row := q.db.QueryRowContext(ctx, getUserTotpInfo, id)
	var i GetUserTotpInfoRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.BackupCodes,
	)
	return i, err
}

const updateUserBackupCodes = `-- name: UpdateUserBackupCodes :exec
UPDATE users SET backup_codes = ? WHERE id = ?
`

type UpdateUserBackupCodesParams struct {
	BackupCodes json.RawMessage `json:"backup_codes"`
	ID          []byte          `json:"id"`
}

func (q *Queries) UpdateUserBackupCodes(ctx context.Context, arg UpdateUserBackupCodesParams) error {
	_, err := q.db.ExecContext(ctx, updateUserBackupCodes, arg.BackupCodes, arg.ID)
	return err
}

const updateUserTotpSecret = `-- name: UpdateUserTotpSecret :exec
UPDATE users SET totp_secret = ? WHERE id = ?
`

type UpdateUserTotpSecretParams struct {
	TotpSecret sql.NullString `json:"totp_secret"`
	ID         []byte         `json:"id"`
}

func (q *Queries) UpdateUserTotpSecret(ctx context.Context, arg UpdateUserTotpSecretParams) error {
	_, err := q.db.ExecContext(ctx, updateUserTotpSecret, arg.TotpSecret, arg.ID)
	return err
}
