// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package repository

import (
	"context"
	"database/sql"
	"time"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, username, email, password, balance)
VALUES (?, ?, ?, ?, 0)
`

type CreateUserParams struct {
	ID       []byte `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.Password,
	)
	return err
}

const deductBalance = `-- name: DeductBalance :execresult
UPDATE users SET balance = balance - ? WHERE id = ? AND balance >= ?
`

type DeductBalanceParams struct {
	Balance   int64  `json:"balance"`
	ID        []byte `json:"id"`
	Balance_2 int64  `json:"balance_2"`
}

func (q *Queries) DeductBalance(ctx context.Context, arg DeductBalanceParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deductBalance, arg.Balance, arg.ID, arg.Balance_2)
}

const depositBalance = `-- name: DepositBalance :execresult
UPDATE users SET balance = balance + ? WHERE id = ?
`

type DepositBalanceParams struct {
	Balance int64  `json:"balance"`
	ID      []byte `json:"id"`
}

func (q *Queries) DepositBalance(ctx context.Context, arg DepositBalanceParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, depositBalance, arg.Balance, arg.ID)
}

const getBalance = `-- name: GetBalance :one
SELECT balance FROM users WHERE id = ?
`

func (q *Queries) GetBalance(ctx context.Context, id []byte) (int64, error) {
	row := q.db.QueryRowContext(ctx, getBalance, id)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password, balance, created_at
FROM users WHERE email = ?
`

type GetUserByEmailRow struct {
	ID        []byte    `json:"id"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	Balance   int64     `json:"balance"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password, balance, created_at
FROM users WHERE id = ?
`

type GetUserByIDRow struct {
	ID        []byte    `json:"id"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	Balance   int64     `json:"balance"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id []byte) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password, balance, created_at
FROM users WHERE username = ?
`

type GetUserByUsernameRow struct {
	ID        []byte    `json:"id"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	Balance   int64     `json:"balance"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}

const refundBalance = `-- name: RefundBalance :exec
UPDATE users SET balance = balance + ? WHERE id = ?
`

type RefundBalanceParams struct {
	Balance int64  `json:"balance"`
	ID      []byte `json:"id"`
}

func (q *Queries) RefundBalance(ctx context.Context, arg RefundBalanceParams) error {
	_, err := q.db.ExecContext(ctx, refundBalance, arg.Balance, arg.ID)
	return err
}
