// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: withdrawals.sql

package repository

import (
	"context"
	"database/sql"
	"time"
)

const countPendingWithdrawalsByUser = `-- name: CountPendingWithdrawalsByUser :one
SELECT COUNT(*) FROM withdrawals WHERE user_id = ? AND status = 'pending'
`

func (q *Queries) CountPendingWithdrawalsByUser(ctx context.Context, userID []byte) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingWithdrawalsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWithdrawal = `-- name: CreateWithdrawal :exec
INSERT INTO withdrawals (id, user_id, amount, status, bank_name, account_number, account_holder, note)
VALUES (?, ?, ?, 'pending', ?, ?, ?, ?)
`

type CreateWithdrawalParams struct {
	ID            []byte `json:"id"`
	UserID        []byte `json:"user_id"`
	Amount        int64  `json:"amount"`
	BankName      string `json:"bank_name"`
	AccountNumber string `json:"account_number"`
	AccountHolder string `json:"account_holder"`
	Note          string `json:"note"`
}

func (q *Queries) CreateWithdrawal(ctx context.Context, arg CreateWithdrawalParams) error {
	_, err := q.db.ExecContext(ctx, createWithdrawal,
		arg.ID,
		arg.UserID,
		arg.Amount,
		arg.BankName,
		arg.AccountNumber,
		arg.AccountHolder,
		arg.Note,
	)
	return err
}

const getWithdrawalByID = `-- name: GetWithdrawalByID :one
SELECT w.id, w.user_id, u.username, w.amount, w.status, w.bank_name, w.account_number, w.account_holder, w.note, w.reviewed_at, w.created_at, w.updated_at
FROM withdrawals w
JOIN users u ON u.id = w.user_id
WHERE w.id = ?
`

type GetWithdrawalByIDRow struct {
	ID            []byte       `json:"id"`
	UserID        []byte       `json:"user_id"`
	Username      string       `json:"username"`
	Amount        int64        `json:"amount"`
	Status        string       `json:"status"`
	BankName      string       `json:"bank_name"`
	AccountNumber string       `json:"account_number"`
	AccountHolder string       `json:"account_holder"`
	Note          string       `json:"note"`
	ReviewedAt    sql.NullTime `json:"reviewed_at"`
	CreatedAt     time.Time    `json:"created_at"`
	UpdatedAt     time.Time    `json:"updated_at"`
}

func (q *Queries) GetWithdrawalByID(ctx context.Context, id []byte) (GetWithdrawalByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getWithdrawalByID, id)
	var i GetWithdrawalByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.Amount,
		&i.Status,
		&i.BankName,
		&i.AccountNumber,
		&i.AccountHolder,
		&i.Note,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWithdrawalsByUser = `-- name: ListWithdrawalsByUser :many
SELECT id, user_id, amount, status, bank_name, account_number, account_holder, note, reviewed_at, created_at, updated_at
FROM withdrawals
WHERE user_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListWithdrawalsByUserParams struct {
	UserID []byte `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListWithdrawalsByUser(ctx context.Context, arg ListWithdrawalsByUserParams) ([]Withdrawal, error) {
	rows, err := q.db.QueryContext(ctx, listWithdrawalsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Withdrawal{}
	for rows.Next() {
		var i Withdrawal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Status,
			&i.BankName,
			&i.AccountNumber,
			&i.AccountHolder,
			&i.Note,
			&i.ReviewedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUserForWithdrawal = `-- name: LockUserForWithdrawal :one
SELECT id, balance FROM users WHERE id = ? FOR UPDATE
`

type LockUserForWithdrawalRow struct {
	ID      []byte `json:"id"`
	Balance int64  `json:"balance"`
}

func (q *Queries) LockUserForWithdrawal(ctx context.Context, id []byte) (LockUserForWithdrawalRow, error) {
	row := q.db.QueryRowContext(ctx, lockUserForWithdrawal, id)
	var i LockUserForWithdrawalRow
	err := row.Scan(&i.ID, &i.Balance)
	return i, err
}

const updateWithdrawalStatus = `-- name: UpdateWithdrawalStatus :exec
UPDATE withdrawals SET status = ?, reviewed_at = NOW() WHERE id = ?
`

type UpdateWithdrawalStatusParams struct {
	Status string `json:"status"`
	ID     []byte `json:"id"`
}

func (q *Queries) UpdateWithdrawalStatus(ctx context.Context, arg UpdateWithdrawalStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateWithdrawalStatus, arg.Status, arg.ID)
	return err
}
